### ISSUE TITLE
[DISEÑO] Detalle de un hotel

### ISSUE THREAD

**Issue by SantiagoMartinez25** [Monterolautaro/Proyecto-Hoteleria#47]
Definir los datos que van a estar disponibles en el detalle de un hotel

**Comment by SantiHerrera18** [comment]
## Creación vista **Hotel Detail** - *13/11/24*

[Click para ver Hotel detail](https://www.figma.com/design/GoE0stmbUcTO5OQzRwlhuA/Hotelify-Figma?node-id=126-13&m=dev)
