### ISSUE TITLE
[DISEÑO] Creación de un hotel y sus habitaciones

### ISSUE THREAD

**Issue by SantiagoMartinez25** [Monterolautaro/Proyecto-Hoteleria#48]
Crear el diseño del flujo de creación de un hotel y sus habitaciones

**Comment by SantiHerrera18** [comment]
[Link de la sección para Hotel Creation](https://www.figma.com/design/GoE0stmbUcTO5OQzRwlhuA/Hotelify-Figma?node-id=222-260&m=dev)
